name: Generate Snake Animation

on:
  schedule:
    # executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
      id-token: write
      pages: write
      actions: read
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests matplotlib pillow
          
      - name: Generate snake animation
        run: |
          python -c "
          import requests
          import json
          import os
          
          # Buscar dados de contribuição
          username = 'DevAlex-full'
          url = f'https://api.github.com/users/{username}/events'
          
          try:
              response = requests.get(url)
              data = response.json()
              
              # Criar um SVG simples da cobra
              svg_content = '''<svg width=\"800\" height=\"200\" xmlns=\"http://www.w3.org/2000/svg\">
                <rect width=\"800\" height=\"200\" fill=\"#0d1117\"/>
                <text x=\"400\" y=\"100\" text-anchor=\"middle\" fill=\"#58a6ff\" font-family=\"monospace\" font-size=\"24\">
                  🐍 Snake Animation - DevAlex-full
                </text>
                <text x=\"400\" y=\"130\" text-anchor=\"middle\" fill=\"#7c3aed\" font-family=\"monospace\" font-size=\"14\">
                  Contribuições em GitHub
                </text>
              </svg>'''
              
              os.makedirs('dist', exist_ok=True)
              with open('dist/snake.svg', 'w') as f:
                  f.write(svg_content)
              print('Snake SVG gerado com sucesso!')
              
          except Exception as e:
              print(f'Erro: {e}')
          "
          
      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/snake.svg
          git commit -m "Update snake animation" || exit 0
          git push
